name: jdih
description: A new Flutter project.


publish_to: "none" 













version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"







dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7

  
  
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  go_router: ^10.0.0
  equatable: ^2.0.5
  path_provider: ^2.0.15
  permission_handler: ^10.4.3
  open_file: ^3.3.2
  flutter_file_downloader: ^1.1.2
  dio: ^5.3.2
  another_flushbar: ^1.12.30
  shimmer: ^3.0.0
  riverpod_annotation:
  shared_preferences:
  freezed_annotation:
  json_annotation:
  hooks_riverpod: ^2.4.0
  flutter_hooks: ^0.20.1
  webview_flutter: ^4.4.1
  rename_app: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed:
  json_serializable:
  riverpod_generator:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

  
  
  
  
  
  flutter_lints: ^2.0.0





flutter:
  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/svg/
    - .env


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logojdih.png"
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
